version: "3"
services: 
  flask:
    container_name: flask
    build: 
      context: .
      dockerfile: Dockerfile-flask
    restart: always
    env_file:
      - ./backend_recs/.env
    ports:
      - "5000:5000"